### ISSUE TITLE
Bug: Language resets after adding a story step

### ISSUE THREAD

**Issue by Thiemann96** [reedu-reengineering-education/mapstories-2.0#210]
0. Create a story 
1. Be in Edit mode 
2. Change the Language 
3. Add a story step 

Sites refreshes and switches back to the old languae. Step is added

**Comment by Mapstories** [comment]
Same occurs in different other scenarios. E.g. changing the language on mapstories.de/de in spanish and clicking on the top left logo, resets the language to german.

**Comment by Mapstories** [comment]
This bug still occurs in various scenarios. Might lead to high frustration, when working with mapstories in a different language.
