### ISSUE TITLE
Translate the login e-mail in the selected language

### ISSUE THREAD

**Issue by Mapstories** [reedu-reengineering-education/mapstories-2.0#239]

**Comment by Thiemann96** [comment]
![image](https://github.com/reedu-reengineering-education/mapstories-2.0/assets/18304210/421e943d-ed5b-4303-8381-3692b1e3b609)

Do you mean the placeholder email in the input field, i.e. to name@beispiel.com? Do I understand correctly?

**Comment by Mapstories** [comment]
![grafik](https://github.com/reedu-reengineering-education/mapstories-2.0/assets/128593592/3da0dccd-5d65-49c1-b0c5-4aca7040c219)

I mean that the text of the email that is sent to you should be in the language that was set before. At the moment the text is always in German.

**Comment by Thiemann96** [comment]
I get it now ! Thanks for the quick answer!

**Comment by Thiemann96** [comment]
As of right now this seems to tedious to implement, I have resorted to displaying the "Copy this link to sign in" in all available languages
