### ISSUE TITLE
Moving the marker does not work properly

### ISSUE THREAD

**Issue by Mapstories** [reedu-reengineering-education/mapstories-2.0#241]
- Sometimes it is not possible to drag the marker
- Sometimes when clicking on a different marker, marker moves to this position

**Comment by Thiemann96** [comment]
Have not been able to reproduce, will keep this open and in mind for further usage.

**Comment by Mapstories** [comment]
Actually you can move the marker if you zoom in close enough, but if you zoom out too far, you can't move it.
