### ISSUE TITLE
Add option for specify sources

### ISSUE THREAD

**Issue by Mapstories** [reedu-reengineering-education/mapstories-2.0#245]
- add input field for text
- add input field for uploading data
- add input field for adding link

**Comment by Thiemann96** [comment]
Media and external links now have an option to provide a source 

![image](https://github.com/reedu-reengineering-education/mapstories-2.0/assets/18304210/6fb22905-cbb0-4b51-8722-caf2fa41fc6b)
![image](https://github.com/reedu-reengineering-education/mapstories-2.0/assets/18304210/f1d8a735-c6b1-442b-a74a-795276430c80)

**Comment by Mapstories** [comment]
Fix Error: If a medium already exists, unfortunately the source information cannot be changed afterwards (Error: no file selected).
