### ISSUE TITLE
iPad: large images hide the button to create the media

### ISSUE THREAD

**Issue by Mapstories** [reedu-reengineering-education/mapstories-2.0#247]

**Comment by Thiemann96** [comment]
Could you provide the image that produces this error?

**Comment by Mapstories** [comment]
I do not have an iPad. This was the feedback we got from students in school. If it doesn't occur anymore, you can close this issue.

**Comment by Thiemann96** [comment]
I'll close it for now, if it occurs again maybe send the image so we can correct. But I tried various big sizes
