### ISSUE TITLE
Fix errors: Working with Timeline Mode

### ISSUE THREAD

**Issue by Mapstories** [reedu-reengineering-education/mapstories-2.0#337]
- [ ] When adding a tag to the title slide after clicking on "Save" the error message "Something went wrong" appears.
- [x] Drag & drop of stations does not work.
- [ ] Labels of the buttons in the timeline are hidden in storylab.
- [x] Application Error: When a Timeline Story is created, the Application Error occurs when My Stories is opened.
- [ ] When a timeline story is shared and then you click on a station in the timeline, it directs you to https://mapstories,de/de.

**Comment by Thiemann96** [comment]
>  When adding a tag after clicking on "Save" the error message "Something went wrong" appears.

I cannot reproduce this, could you try again with a different story, or share the tag that you wanted to input? 

> Drag & drop of stations does not work 

Is working as intended as drag & drop makes no sense with a specific time of the stations

>  Labels of the buttons in the timeline are hidden in storylab.

I don't know what you mean, could you provide pictures, please? 

>  Application Error: When a Timeline Story is created, the Application Error occurs when My Stories is opened.

Can't reproduce also, could you provide additional information, for example if this is the only mapstory that is registered to your account or any other information that might help to reproduce this? 

>  Application Error: When a timeline story is shared and then you click on a station in the timeline, the Application Error occurs.

Same as above, can not seem to reproduce. What excatly do you mean by clicking on a station (timeline or marker?)  Although we recently fixed a bug where the a click on a marker would redirect you to a wrong page.

**Comment by Mapstories** [comment]
> > When adding a tag after clicking on "Save" the error message "Something went wrong" appears.
> 
> I cannot reproduce this, could you try again with a different story, or share the tag that you wanted to input?
> 
Actually this only occurs on the title slide.

> > Drag & drop of stations does not work
> 
> Is working as intended as drag & drop makes no sense with a specific time of the stations
> 
Okay, I checked this point above.
> > Labels of the buttons in the timeline are hidden in storylab.
> 
> I don't know what you mean, could you provide pictures, please?
> 
![grafik](https://github.com/reedu-reengineering-education/mapstories-2.0/assets/128593592/f0f86e42-6bb2-404e-b870-4f967567322e)

> > Application Error: When a Timeline Story is created, the Application Error occurs when My Stories is opened.
> 
> Can't reproduce also, could you provide additional information, for example if this is the only mapstory that is registered to your account or any other information that might help to reproduce this?
> 
I can't reproduce it anymore, aswell. It did come up though. I checked the error above.
> > Application Error: When a timeline story is shared and then you click on a station in the timeline, the Application Error occurs.
> 
> Same as above, can not seem to reproduce. What excatly do you mean by clicking on a station (timeline or marker?) Although we recently fixed a bug where the a click on a marker would redirect you to a wrong page.

Can't reproduce the application error also. But when you click on the station in the timeline, you get directed to https://mapstories.de/de and not to the correct station. I changed the bulletpoint above.

**Comment by Thiemann96** [comment]
Thanks for the quick answer, will check it now !

**Comment by Thiemann96** [comment]
> Can't reproduce the application error also. But when you click on the station in the timeline, you get directed to https://mapstories.de/de and not to the correct station. I changed the bulletpoint above.

Still can't seem to get this, could you share your story with me, please ?

**Comment by Mapstories** [comment]
> > Can't reproduce the application error also. But when you click on the station in the timeline, you get directed to https://mapstories.de/de and not to the correct station. I changed the bulletpoint above.
> 
> Still can't seem to get this, could you share your story with me, please ?

This is an example of a mapstory. Maybe it only occurs when you are not logged in.

https://mapstories.de/gallery/all/story/clmkj6av0006pqj0sinit2xqr/start

**Comment by Thiemann96** [comment]
yes it only occurs when not logged in! working on it, thanks !
