### ISSUE TITLE
Fix various bugs in mobile version

### ISSUE THREAD

**Issue by Mapstories** [reedu-reengineering-education/mapstories-2.0#352]
- [x] When holding the phone in horizontal mode, on the homepage of mapstories the map is not zoomable or moveable
- [x] Zooming into the mediabox leads to message "Smartphone in landscape mode" in mobile viewer
- [x] Scrolling down in mediabox sometimes leads to swiping a slide (->Issue #353)
- [ ] Instagram, Spotify, TikTok, ... media have wrong scaling in mediabox
- [x] When opening the "menu" of mapstories (top left corner) in viewer, the menu is shown in a layer behind the marker and the arrow
- [x] Menu is cut off when opening in vertical mode on homepage of mapstories

**Comment by Thiemann96** [comment]
Fixed display issues, embed issues will be adressed in another issue
