### ISSUE TITLE
Styles for markdown editor

### ISSUE THREAD

**Issue by Thiemann96** [reedu-reengineering-education/mapstories-2.0#50]
Set control bars
Set background color 

In preview sidebar: 
 Text has no onHover effect

**Comment by Mapstories** [comment]
I would prefer a different text editor to improve the usability. The formatting of the text is quite complicated with this markdown editor.

**Comment by Thiemann96** [comment]
![grafik](https://github.com/user-attachments/assets/c1603c70-0882-4627-8e78-560ab1d318e6)
